title: "Dr Jorge Campos González"
description: "Senior Research Fellow in agri-food economics, AI, labour markets, productivity and sustainable food systems."
url: "https://jorgecamposgonzalez.github.io"
markdown: kramdown
cloudflare_web_analytics_token: "0d3158cd9c974032b47cb200f0b66942"
